# Generated by Django 4.2.24 on 2025-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Smart Tracking Platform", max_length=100),
                ),
                ("navbar_color", models.CharField(default="dark", max_length=20)),
                ("enable_cameras", models.BooleanField(default=True)),
                ("enable_tracking", models.BooleanField(default=True)),
                (
                    "advanced_tracking_options",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
