# Generated by Django 4.2.24 on 2025-09-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sitesettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="enable_cameras",
            new_name="cameras_enabled",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="enable_tracking",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="advanced_tracking_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Advanced tracking options in JSON format",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="navbar_color",
            field=models.CharField(
                choices=[
                    ("primary", "Blue"),
                    ("dark", "Dark"),
                    ("light", "Light"),
                    ("success", "Green"),
                    ("warning", "Yellow"),
                    ("danger", "Red"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
    ]
