# Generated by Django 4.2.24 on 2025-09-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_rename_enable_cameras_sitesettings_cameras_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="advanced_tracking_options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
