# Generated by Django 4.2.24 on 2025-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rtsp", "RTSP"),
                            ("file", "Video File"),
                            ("stream", "HTTP Stream"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
