# Generated by Django 4.2.24 on 2025-09-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.IntegerField(blank=True, null=True)),
                ("label", models.CharField(max_length=100)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("bbox", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                ("frame_number", models.IntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cameras.camera",
                    ),
                ),
            ],
        ),
    ]
