# Generated by Django 4.2.24 on 2025-09-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanted", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wantedperson",
            name="face_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
